/** Banco do Tio Mário Milionário — alts[0] é SEMPRE a correta (o servidor embaralha). */
export interface MilhaoPergunta {
  categoria: string
  texto: string
  /** 4 alternativas ÚNICAS; a PRIMEIRA é a correta */
  alts: [string, string, string, string]
}

export const MILHAO_FACIL: MilhaoPergunta[] = [
  { categoria: 'Geografia', texto: 'Qual é a capital do Brasil?', alts: ['Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador'] },
  { categoria: 'Matemática', texto: 'Quantos lados tem um triângulo?', alts: ['3', '4', '5', '6'] },
  { categoria: 'Geografia', texto: 'Qual é o maior país do mundo em área territorial?', alts: ['Rússia', 'Canadá', 'China', 'Estados Unidos'] },
  { categoria: 'Natureza', texto: 'Qual é o maior oceano do mundo?', alts: ['Oceano Pacífico', 'Oceano Atlântico', 'Oceano Índico', 'Oceano Ártico'] },
  { categoria: 'Corpo humano', texto: 'Aproximadamente quantos ossos tem o esqueleto de um adulto?', alts: ['206', '150', '300', '500'] },
  { categoria: 'Ciência', texto: 'Em qual estado físico a água se transforma ao congelar a 0°C?', alts: ['Sólido', 'Líquido', 'Gasoso', 'Plasma'] },
  { categoria: 'Esportes', texto: 'Quantos jogadores de cada time ficam em campo em uma partida de futebol?', alts: ['11', '10', '9', '12'] },
  { categoria: 'Cultura', texto: 'Quem pintou o quadro "Mona Lisa"?', alts: ['Leonardo da Vinci', 'Michelangelo', 'Rafael Sanzio', 'Pablo Picasso'] },
  { categoria: 'Português', texto: 'Qual é o plural correto da palavra "pão"?', alts: ['Pães', 'Pãos', 'Pões', 'Pãezes'] },
  { categoria: 'Geografia', texto: 'Qual é a capital da França?', alts: ['Paris', 'Londres', 'Roma', 'Madri'] },
  { categoria: 'Matemática', texto: 'Quanto é 7 x 8?', alts: ['56', '54', '64', '48'] },
  { categoria: 'Natureza', texto: 'Qual é o maior mamífero do mundo?', alts: ['Baleia-azul', 'Elefante-africano', 'Girafa', 'Tubarão-baleia'] },
  { categoria: 'Esportes', texto: 'Qual esporte de raquete, disputado com bola em quadra dividida por rede, é o principal de Wimbledon?', alts: ['Tênis', 'Badminton', 'Squash', 'Tênis de mesa'] },
  { categoria: 'História', texto: 'Em que ano os portugueses chegaram ao Brasil?', alts: ['1500', '1492', '1600', '1822'] },
  { categoria: 'Cultura', texto: 'Qual instrumento musical possui teclas brancas e pretas?', alts: ['Piano', 'Violão', 'Flauta', 'Bateria'] },
  { categoria: 'Corpo humano', texto: 'Qual órgão é responsável por bombear o sangue pelo corpo?', alts: ['Coração', 'Pulmão', 'Fígado', 'Rim'] },
  { categoria: 'Geografia', texto: 'Qual é o maior país da América do Sul em área?', alts: ['Brasil', 'Argentina', 'Peru', 'Colômbia'] },
  { categoria: 'Ciência', texto: 'Qual planeta do Sistema Solar é conhecido como "Planeta Vermelho"?', alts: ['Marte', 'Vênus', 'Júpiter', 'Saturno'] },
  { categoria: 'Matemática', texto: 'Quanto é a metade de 100?', alts: ['50', '25', '75', '45'] },
  { categoria: 'Português', texto: 'Qual das palavras abaixo é um verbo?', alts: ['Correr', 'Mesa', 'Azul', 'Rápido'] },
  { categoria: 'Esportes', texto: 'Qual país sediou a Copa do Mundo de futebol de 2014?', alts: ['Brasil', 'Alemanha', 'África do Sul', 'Rússia'] },
  { categoria: 'Natureza', texto: 'Qual é o maior deserto quente do mundo?', alts: ['Deserto do Saara', 'Deserto de Gobi', 'Deserto do Atacama', 'Deserto do Kalahari'] },
  { categoria: 'Tecnologia', texto: 'O que significa a sigla "PC" em informática?', alts: ['Computador pessoal', 'Programa completo', 'Ponto de controle', 'Processo contínuo'] },
  { categoria: 'Cultura', texto: 'Quantas cordas tem um violão comum de 6 cordas simples?', alts: ['6', '4', '5', '8'] },
  { categoria: 'História', texto: 'Quem proclamou a independência do Brasil em 1822?', alts: ['Dom Pedro I', 'Dom Pedro II', 'Tiradentes', 'Getúlio Vargas'] },
  { categoria: 'Geografia', texto: 'Qual é o rio mais extenso dentro do território brasileiro?', alts: ['Rio Amazonas', 'Rio São Francisco', 'Rio Tocantins', 'Rio Paraná'] },
  { categoria: 'Matemática', texto: 'Quanto é 9 menos 4?', alts: ['5', '6', '4', '3'] },
  { categoria: 'Corpo humano', texto: 'Quantos sentidos básicos são tradicionalmente atribuídos ao ser humano?', alts: ['5', '4', '6', '3'] },
  { categoria: 'Ciência', texto: 'Qual gás os seres humanos precisam respirar para sobreviver?', alts: ['Oxigênio', 'Gás carbônico', 'Nitrogênio', 'Hidrogênio'] },
  { categoria: 'Esportes', texto: 'Quantos jogadores de cada time ficam em quadra em uma partida de vôlei?', alts: ['6', '5', '7', '4'] },
  { categoria: 'Cultura', texto: 'Em qual país fica a Torre Eiffel?', alts: ['França', 'Itália', 'Espanha', 'Alemanha'] },
  { categoria: 'Português', texto: 'Qual é um sinônimo da palavra "feliz"?', alts: ['Contente', 'Triste', 'Bravo', 'Cansado'] },
]

export const MILHAO_MEDIO: MilhaoPergunta[] = [
  { categoria: 'Geografia', texto: 'Qual é o rio mais extenso do mundo?', alts: ['Rio Amazonas', 'Rio Nilo', 'Rio Mississippi', 'Rio Yangtzé'] },
  { categoria: 'Cultura', texto: 'Quem escreveu o romance "Dom Casmurro"?', alts: ['Machado de Assis', 'José de Alencar', 'Guimarães Rosa', 'Jorge Amado'] },
  { categoria: 'História', texto: 'Em que ano começou a Segunda Guerra Mundial?', alts: ['1939', '1914', '1945', '1929'] },
  { categoria: 'Ciência', texto: 'Qual é o símbolo químico do elemento ouro?', alts: ['Au', 'Ag', 'Fe', 'Pb'] },
  { categoria: 'Matemática', texto: 'Quanto é a raiz quadrada de 81?', alts: ['9', '8', '7', '11'] },
  { categoria: 'Esportes', texto: 'Em que ano o Brasil conquistou seu primeiro título de Copa do Mundo de futebol?', alts: ['1958', '1950', '1962', '1970'] },
  { categoria: 'Geografia', texto: 'Qual é considerado o menor país do mundo em área territorial?', alts: ['Vaticano', 'Mônaco', 'San Marino', 'Liechtenstein'] },
  { categoria: 'Corpo humano', texto: 'Qual é o maior órgão do corpo humano?', alts: ['Pele', 'Fígado', 'Pulmão', 'Intestino'] },
  { categoria: 'Português', texto: 'Qual é a classe gramatical da palavra "rapidamente"?', alts: ['Advérbio', 'Adjetivo', 'Substantivo', 'Pronome'] },
  { categoria: 'História', texto: 'Quem foi o primeiro presidente do Brasil?', alts: ['Deodoro da Fonseca', 'Getúlio Vargas', 'Prudente de Morais', 'Floriano Peixoto'] },
  { categoria: 'Natureza', texto: 'Qual é o animal terrestre mais rápido do mundo?', alts: ['Guepardo', 'Leão', 'Cavalo', 'Avestruz'] },
  { categoria: 'Ciência', texto: 'Qual é a unidade básica de todo ser vivo?', alts: ['Célula', 'Átomo', 'Molécula', 'Tecido'] },
  { categoria: 'Cultura', texto: 'Qual pintora brasileira criou a obra "Abaporu"?', alts: ['Tarsila do Amaral', 'Cândido Portinari', 'Di Cavalcanti', 'Anita Malfatti'] },
  { categoria: 'Geografia', texto: 'Qual é a capital da Austrália?', alts: ['Camberra', 'Sydney', 'Melbourne', 'Perth'] },
  { categoria: 'Matemática', texto: 'Quantos graus soma os ângulos internos de um triângulo?', alts: ['180', '360', '90', '270'] },
  { categoria: 'Esportes', texto: 'Quantos anéis entrelaçados tem a bandeira olímpica?', alts: ['5', '4', '6', '7'] },
  { categoria: 'História', texto: 'Qual civilização construiu as pirâmides de Gizé, no Egito?', alts: ['Egípcios', 'Maias', 'Incas', 'Romanos'] },
  { categoria: 'Tecnologia', texto: 'O que significa a sigla "WWW", usada em endereços da internet?', alts: ['World Wide Web', 'World Wide Wire', 'Web Wide World', 'Wide World Web'] },
  { categoria: 'Português', texto: 'Qual é o antônimo da palavra "generoso"?', alts: ['Mesquinho', 'Gentil', 'Alegre', 'Sincero'] },
  { categoria: 'Natureza', texto: 'Qual é o nome do processo pelo qual as plantas produzem seu próprio alimento usando luz solar?', alts: ['Fotossíntese', 'Respiração', 'Transpiração', 'Germinação'] },
  { categoria: 'Corpo humano', texto: 'Quantas câmaras tem o coração humano?', alts: ['4', '2', '3', '5'] },
  { categoria: 'Geografia', texto: 'Qual é o continente mais populoso do mundo?', alts: ['Ásia', 'África', 'Europa', 'América'] },
  { categoria: 'Ciência', texto: 'Qual é a velocidade aproximada da luz no vácuo?', alts: ['300 mil km/s', '150 mil km/s', '1 milhão de km/s', '30 mil km/s'] },
  { categoria: 'Cultura', texto: 'O samba, como gênero musical reconhecido, nasceu em qual país?', alts: ['Brasil', 'Portugal', 'Angola', 'Cuba'] },
  { categoria: 'Matemática', texto: 'Quanto é 15% de 200?', alts: ['30', '20', '15', '40'] },
  { categoria: 'Esportes', texto: 'Em qual modalidade esportiva é disputada a Copa Davis?', alts: ['Tênis', 'Golfe', 'Vôlei', 'Atletismo'] },
  { categoria: 'História', texto: 'Quem foi o primeiro ser humano a pisar na Lua?', alts: ['Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'John Glenn'] },
  { categoria: 'Natureza', texto: 'Qual é o maior felino selvagem do mundo?', alts: ['Tigre', 'Leão', 'Onça-pintada', 'Leopardo'] },
  { categoria: 'Português', texto: 'Como se chama a figura de linguagem que atribui características humanas a seres inanimados?', alts: ['Personificação', 'Metáfora', 'Hipérbole', 'Ironia'] },
  { categoria: 'Geografia', texto: 'Qual é a maior cordilheira do mundo em extensão?', alts: ['Andes', 'Himalaia', 'Alpes', 'Montanhas Rochosas'] },
  { categoria: 'Tecnologia', texto: 'Quem é reconhecido como o inventor do telefone?', alts: ['Alexander Graham Bell', 'Thomas Edison', 'Nikola Tesla', 'Guglielmo Marconi'] },
  { categoria: 'Ciência', texto: 'Qual órgão do corpo humano produz o hormônio insulina?', alts: ['Pâncreas', 'Fígado', 'Rim', 'Baço'] },
]

export const MILHAO_DIFICIL: MilhaoPergunta[] = [
  { categoria: 'Ciência', texto: 'Qual é o elemento químico cujo símbolo na tabela periódica é "W"?', alts: ['Tungstênio', 'Tório', 'Tálio', 'Tecnécio'] },
  { categoria: 'Geografia', texto: 'Qual país possui o maior número de fusos horários em seu território, contando territórios ultramarinos?', alts: ['França', 'Rússia', 'Estados Unidos', 'China'] },
  { categoria: 'História', texto: 'Em que ano ocorreu a Queda do Muro de Berlim?', alts: ['1989', '1991', '1985', '1979'] },
  { categoria: 'Cultura', texto: 'Quem compôs a ópera "Carmen"?', alts: ['Georges Bizet', 'Giuseppe Verdi', 'Giacomo Puccini', 'Wolfgang Amadeus Mozart'] },
  { categoria: 'Matemática', texto: 'Qual é o valor aproximado do número de Euler (e)?', alts: ['2,718', '3,141', '1,618', '1,414'] },
  { categoria: 'Esportes', texto: 'Em qual país foi realizada a primeira Copa do Mundo de futebol, em 1930?', alts: ['Uruguai', 'Brasil', 'Itália', 'França'] },
  { categoria: 'Geografia', texto: 'Onde fica o ponto mais profundo já registrado nos oceanos?', alts: ['Fossa das Marianas', 'Fossa de Porto Rico', 'Fossa das Tonga', 'Fossa do Peru-Chile'] },
  { categoria: 'Ciência', texto: 'Qual cientista formulou a Lei da Gravitação Universal?', alts: ['Isaac Newton', 'Albert Einstein', 'Galileu Galilei', 'Johannes Kepler'] },
  { categoria: 'Corpo humano', texto: 'Qual é o menor osso do corpo humano, localizado no ouvido?', alts: ['Estribo', 'Martelo', 'Bigorna', 'Fêmur'] },
  { categoria: 'História', texto: 'Quem foi o principal líder da Revolução Russa de 1917?', alts: ['Vladimir Lênin', 'Joseph Stalin', 'Leon Trótski', 'Nicolau II'] },
  { categoria: 'Cultura', texto: 'Qual escritor português é autor do poema épico "Os Lusíadas"?', alts: ['Luís de Camões', 'Fernando Pessoa', 'José Saramago', 'Eça de Queirós'] },
  { categoria: 'Matemática', texto: 'Quantos lados tem um icoságono?', alts: ['20', '12', '15', '18'] },
  { categoria: 'Geografia', texto: 'Qual é a capital da Mongólia?', alts: ['Ulan Bator', 'Astana', 'Bishkek', 'Tashkent'] },
  { categoria: 'Ciência', texto: 'Qual é o gás mais abundante na atmosfera terrestre?', alts: ['Nitrogênio', 'Oxigênio', 'Gás carbônico', 'Argônio'] },
  { categoria: 'Esportes', texto: 'Em que ano foram realizados os primeiros Jogos Olímpicos da era moderna?', alts: ['1896', '1900', '1924', '1886'] },
  { categoria: 'Português', texto: 'Como se chama o uso de uma palavra vinda de outra língua sem tradução, como "shopping"?', alts: ['Estrangeirismo', 'Neologismo', 'Arcaísmo', 'Regionalismo'] },
  { categoria: 'História', texto: 'Qual tratado pôs fim oficialmente à Primeira Guerra Mundial?', alts: ['Tratado de Versalhes', 'Tratado de Tordesilhas', 'Tratado de Utrecht', 'Tratado de Paris'] },
  { categoria: 'Natureza', texto: 'Qual é o único mamífero capaz de voar de forma ativa e batendo asas?', alts: ['Morcego', 'Esquilo-voador', 'Falcão', 'Pterossauro'] },
  { categoria: 'Cultura', texto: 'Quem compôs a sinfonia conhecida por trazer o "Hino à Alegria" em seu movimento final?', alts: ['Ludwig van Beethoven', 'Johann Sebastian Bach', 'Wolfgang Amadeus Mozart', 'Franz Schubert'] },
  { categoria: 'Geografia', texto: 'Qual é o país de maior extensão territorial da África?', alts: ['Argélia', 'República Democrática do Congo', 'Sudão', 'Líbia'] },
  { categoria: 'Ciência', texto: 'Qual é a unidade de medida da resistência elétrica no Sistema Internacional?', alts: ['Ohm', 'Watt', 'Volt', 'Ampère'] },
  { categoria: 'Matemática', texto: 'Qual é o resultado de 2 elevado à décima potência (2¹⁰)?', alts: ['1024', '512', '2048', '1000'] },
  { categoria: 'Esportes', texto: 'Qual seleção foi a primeira a conquistar cinco títulos de Copa do Mundo de futebol masculino?', alts: ['Brasil', 'Alemanha', 'Itália', 'Argentina'] },
  { categoria: 'Corpo humano', texto: 'Qual é a maior artéria do corpo humano?', alts: ['Aorta', 'Veia cava', 'Artéria pulmonar', 'Artéria carótida'] },
  { categoria: 'História', texto: 'Qual imperador romano assinou o Edito de Milão, legalizando o cristianismo no império?', alts: ['Constantino', 'Nero', 'Diocleciano', 'Augusto'] },
  { categoria: 'Tecnologia', texto: 'Quem é considerado o criador da linguagem HTML e o inventor da World Wide Web?', alts: ['Tim Berners-Lee', 'Bill Gates', 'Steve Jobs', 'Linus Torvalds'] },
  { categoria: 'Cultura', texto: 'Qual movimento artístico brasileiro teve a Semana de Arte Moderna de 1922 como marco inicial?', alts: ['Modernismo', 'Barroco', 'Romantismo', 'Impressionismo'] },
  { categoria: 'Geografia', texto: 'Qual é o lago mais profundo do mundo?', alts: ['Lago Baikal', 'Lago Superior', 'Lago Vitória', 'Mar Cáspio'] },
  { categoria: 'Matemática', texto: 'Como se chama um polígono de sete lados?', alts: ['Heptágono', 'Hexágono', 'Octógono', 'Pentágono'] },
  { categoria: 'Ciência', texto: 'Como se chama o tipo de divisão celular que origina os gametas (células reprodutivas)?', alts: ['Meiose', 'Mitose', 'Citocinese', 'Fecundação'] },
  { categoria: 'Português', texto: 'Qual é o termo linguístico para uma mesma palavra que possui múltiplos significados relacionados entre si?', alts: ['Polissemia', 'Homonímia', 'Sinonímia', 'Antonímia'] },
  { categoria: 'História', texto: 'Em que século nasceu o artista e inventor renascentista Leonardo da Vinci?', alts: ['Século XV', 'Século XIII', 'Século XVII', 'Século XI'] },
]
