/**
 * Bancos de perguntas dos quizzes — VIVEM SÓ NO SERVIDOR (a alternativa
 * correta é sempre a PRIMEIRA; o módulo embaralha por partida e nunca
 * envia a certa antes da revelação). Expansão dos bancos = melhoria
 * contínua; manter respostas inequívocas e datadas com cuidado.
 */

export interface QuizPergunta {
  /** categoria exibida no card */
  c: string
  p: string
  /** alts[0] é SEMPRE a correta (embaralhada por partida no init) */
  alts: [string, string, string, string]
}

export const QUIZ_POP: QuizPergunta[] = [
  { c: 'Geografia', p: 'Qual é a capital do Brasil?', alts: ['Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador'] },
  { c: 'Geografia', p: 'Qual é o maior estado do Brasil em área?', alts: ['Amazonas', 'Pará', 'Mato Grosso', 'Bahia'] },
  { c: 'Geografia', p: 'Que rio corta a cidade de Manaus?', alts: ['Rio Negro', 'Rio São Francisco', 'Rio Tietê', 'Rio Paraná'] },
  { c: 'Geografia', p: 'Qual país faz fronteira com o Brasil ao sul?', alts: ['Uruguai', 'Chile', 'Equador', 'Panamá'] },
  { c: 'Geografia', p: 'Em que estado fica a Chapada Diamantina?', alts: ['Bahia', 'Goiás', 'Minas Gerais', 'Tocantins'] },
  { c: 'Geografia', p: 'Qual é o ponto mais alto do Brasil?', alts: ['Pico da Neblina', 'Pico da Bandeira', 'Pedra da Mina', 'Monte Roraima'] },
  { c: 'Geografia', p: 'Qual oceano banha o litoral brasileiro?', alts: ['Atlântico', 'Pacífico', 'Índico', 'Ártico'] },
  { c: 'Geografia', p: 'Qual é a capital do Ceará?', alts: ['Fortaleza', 'Natal', 'Teresina', 'São Luís'] },
  { c: 'Ciência', p: 'Qual planeta é conhecido como Planeta Vermelho?', alts: ['Marte', 'Vênus', 'Júpiter', 'Mercúrio'] },
  { c: 'Ciência', p: 'Quantos ossos tem o corpo humano adulto?', alts: ['206', '186', '226', '250'] },
  { c: 'Ciência', p: 'Qual é o símbolo químico do ouro?', alts: ['Au', 'Ag', 'Or', 'Go'] },
  { c: 'Ciência', p: 'Que gás as plantas absorvem na fotossíntese?', alts: ['Gás carbônico', 'Oxigênio', 'Nitrogênio', 'Hidrogênio'] },
  { c: 'Ciência', p: 'Qual é o maior órgão do corpo humano?', alts: ['A pele', 'O fígado', 'O pulmão', 'O intestino'] },
  { c: 'Ciência', p: 'Quantos planetas tem o Sistema Solar?', alts: ['8', '9', '7', '10'] },
  { c: 'Ciência', p: 'O que mede a escala Richter?', alts: ['Terremotos', 'Furacões', 'Chuva', 'Temperatura'] },
  { c: 'Ciência', p: 'Qual animal é o mamífero mais rápido do mundo?', alts: ['Guepardo', 'Leão', 'Cavalo', 'Antílope'] },
  { c: 'Esportes', p: 'Quantos jogadores tem um time de futebol em campo?', alts: ['11', '10', '12', '9'] },
  { c: 'Esportes', p: 'Quantos pontos vale uma cesta de fora do garrafão no basquete?', alts: ['3', '2', '1', '4'] },
  { c: 'Esportes', p: 'Em que esporte se usa o termo "ippon"?', alts: ['Judô', 'Boxe', 'Esgrima', 'Ginástica'] },
  { c: 'Esportes', p: 'Qual país criou o vôlei de praia como esporte olímpico dominante?', alts: ['Brasil', 'Itália', 'Cuba', 'Rússia'] },
  { c: 'Esportes', p: 'De quantos em quantos anos acontecem os Jogos Olímpicos de verão?', alts: ['4', '2', '3', '5'] },
  { c: 'Esportes', p: 'No vôlei, quantos toques a equipe pode dar antes de passar a bola?', alts: ['3', '2', '4', '5'] },
  { c: 'Esportes', p: 'Qual seleção venceu a primeira Copa do Mundo, em 1930?', alts: ['Uruguai', 'Brasil', 'Argentina', 'Itália'] },
  { c: 'Cultura', p: 'Quem pintou a Mona Lisa?', alts: ['Leonardo da Vinci', 'Michelangelo', 'Van Gogh', 'Picasso'] },
  { c: 'Cultura', p: 'Quem escreveu "Dom Casmurro"?', alts: ['Machado de Assis', 'José de Alencar', 'Jorge Amado', 'Graciliano Ramos'] },
  { c: 'Cultura', p: 'Qual instrumento tem 88 teclas?', alts: ['Piano', 'Órgão', 'Acordeom', 'Cravo'] },
  { c: 'Cultura', p: 'De que país vem a pizza?', alts: ['Itália', 'França', 'Grécia', 'Espanha'] },
  { c: 'Cultura', p: 'Qual é o idioma mais falado no mundo (nativos)?', alts: ['Mandarim', 'Inglês', 'Espanhol', 'Hindi'] },
  { c: 'Cultura', p: 'O frevo é um ritmo típico de qual estado?', alts: ['Pernambuco', 'Bahia', 'Rio de Janeiro', 'Maranhão'] },
  { c: 'Cultura', p: 'Quem escreveu "O Pequeno Príncipe"?', alts: ['Saint-Exupéry', 'Julio Verne', 'Monteiro Lobato', 'Lewis Carroll'] },
  { c: 'História', p: 'Em que ano o Brasil proclamou a independência?', alts: ['1822', '1889', '1500', '1808'] },
  { c: 'História', p: 'Quem foi a princesa que assinou a Lei Áurea?', alts: ['Princesa Isabel', 'Dona Leopoldina', 'Maria I', 'Carlota Joaquina'] },
  { c: 'História', p: 'Qual navegador chegou ao Brasil em 1500?', alts: ['Pedro Álvares Cabral', 'Cristóvão Colombo', 'Vasco da Gama', 'Fernão de Magalhães'] },
  { c: 'História', p: 'Que muro caiu em 1989, símbolo da Guerra Fria?', alts: ['Muro de Berlim', 'Muralha da China', 'Muro de Varsóvia', 'Muro de Moscou'] },
  { c: 'História', p: 'Qual civilização construiu as pirâmides de Gizé?', alts: ['Egípcia', 'Maia', 'Romana', 'Grega'] },
  { c: 'História', p: 'Quem foi o primeiro presidente do Brasil?', alts: ['Deodoro da Fonseca', 'Getúlio Vargas', 'Floriano Peixoto', 'Prudente de Morais'] },
  { c: 'Comida', p: 'Qual é o ingrediente principal do brigadeiro?', alts: ['Leite condensado', 'Creme de leite', 'Doce de leite', 'Leite em pó'] },
  { c: 'Comida', p: 'De que região vem o acarajé?', alts: ['Bahia', 'Minas Gerais', 'Pará', 'Rio Grande do Sul'] },
  { c: 'Comida', p: 'Qual fruta é a base do guacamole?', alts: ['Abacate', 'Tomate', 'Pimentão', 'Manga'] },
  { c: 'Comida', p: 'O pão de queijo é típico de qual estado?', alts: ['Minas Gerais', 'São Paulo', 'Paraná', 'Goiás'] },
  { c: 'Comida', p: 'Qual massa é usada no pastel de feira?', alts: ['Massa de pastel', 'Massa folhada', 'Massa filo', 'Massa brisée'] },
  { c: 'Comida', p: 'Tacacá é um prato típico de qual região do Brasil?', alts: ['Norte', 'Sul', 'Sudeste', 'Centro-Oeste'] },
  { c: 'Bichos', p: 'Qual é o maior animal do planeta?', alts: ['Baleia-azul', 'Elefante-africano', 'Girafa', 'Tubarão-baleia'] },
  { c: 'Bichos', p: 'Quantas patas tem uma aranha?', alts: ['8', '6', '10', '12'] },
  { c: 'Bichos', p: 'Qual ave brasileira é símbolo do Pantanal?', alts: ['Tuiuiú', 'Arara-azul', 'Tucano', 'Gavião-real'] },
  { c: 'Bichos', p: 'O que o bicho-preguiça come principalmente?', alts: ['Folhas', 'Frutas', 'Insetos', 'Peixes'] },
  { c: 'Bichos', p: 'Qual é o único mamífero que voa de verdade?', alts: ['Morcego', 'Esquilo-voador', 'Petauro', 'Colugo'] },
  { c: 'Bichos', p: 'Qual animal muda de cor para se camuflar?', alts: ['Camaleão', 'Iguana', 'Salamandra', 'Lagartixa'] },
]

export const QUIZ_NOSTALGIA: QuizPergunta[] = [
  { c: 'Música', p: 'Quem é o "Rei" da música brasileira?', alts: ['Roberto Carlos', 'Erasmo Carlos', 'Tim Maia', 'Wando'] },
  { c: 'Música', p: 'Qual dupla caipira gravou "Fio de Cabelo"?', alts: ['Chitãozinho & Xororó', 'Zezé Di Camargo & Luciano', 'Leandro & Leonardo', 'Tonico & Tinoco'] },
  { c: 'Música', p: 'Que movimento musical Caetano e Gil lideraram nos anos 60?', alts: ['Tropicália', 'Bossa Nova', 'Jovem Guarda', 'Clube da Esquina'] },
  { c: 'Música', p: '"Garota de Ipanema" é de Tom Jobim e…', alts: ['Vinicius de Moraes', 'Chico Buarque', 'Dorival Caymmi', 'Ary Barroso'] },
  { c: 'Música', p: 'Qual cantora era conhecida como "A Pequena Notável"?', alts: ['Carmen Miranda', 'Elis Regina', 'Dalva de Oliveira', 'Emilinha Borba'] },
  { c: 'Música', p: 'Quem cantava "Meu Pintinho Amarelinho" nos programas infantis?', alts: ['Gugu Liberato', 'Xuxa', 'Angélica', 'Mara Maravilha'] },
  { c: 'Música', p: 'Qual banda de Brasília gravou "Que País É Este"?', alts: ['Legião Urbana', 'Capital Inicial', 'Paralamas do Sucesso', 'Titãs'] },
  { c: 'Música', p: 'A Jovem Guarda tinha Roberto, Erasmo e…', alts: ['Wanderléa', 'Rita Lee', 'Gal Costa', 'Marina Lima'] },
  { c: 'Música', p: 'Quem compôs "Aquarela do Brasil"?', alts: ['Ary Barroso', 'Pixinguinha', 'Noel Rosa', 'Lamartine Babo'] },
  { c: 'Novelas', p: 'Em que novela o vilão Odete Roitman foi assassinada?', alts: ['Vale Tudo', 'Roque Santeiro', 'Dancin Days', 'Tieta'] },
  { c: 'Novelas', p: 'Quem viveu a icônica Viúva Porcina em Roque Santeiro?', alts: ['Regina Duarte', 'Susana Vieira', 'Gloria Menezes', 'Betty Faria'] },
  { c: 'Novelas', p: 'Qual novela tinha o bordão "Ó coitado!" do Seu Boneco?', alts: ['O Bem-Amado', 'Gabriela', 'Saramandaia', 'Pedra sobre Pedra'] },
  { c: 'Novelas', p: '"Escrava Isaura" (1976) foi vivida por qual atriz?', alts: ['Lucélia Santos', 'Sônia Braga', 'Regina Duarte', 'Vera Fischer'] },
  { c: 'Novelas', p: 'Sinhozinho Malta, de Roque Santeiro, era interpretado por…', alts: ['Lima Duarte', 'Tarcísio Meira', 'Antônio Fagundes', 'Raul Cortez'] },
  { c: 'Novelas', p: 'Qual novela das oito parou o Brasil com a pergunta "Quem matou Salomão Hayalla?"', alts: ['O Astro', 'Pai Herói', 'Baila Comigo', 'Água Viva'] },
  { c: 'TV', p: 'Quem apresentava o programa de calouros "Show de Calouros"?', alts: ['Silvio Santos', 'Chacrinha', 'Flávio Cavalcanti', 'Raul Gil'] },
  { c: 'TV', p: '"Terra do Nunca, lá vou eu!" era o grito de qual programa?', alts: ['Balão Mágico', 'Xou da Xuxa', 'Bambalalão', 'Sítio do Picapau Amarelo'] },
  { c: 'TV', p: 'Qual palhaço comandava as tardes com "Bozo"? Era transmitido pela…', alts: ['SBT', 'Globo', 'Band', 'Manchete'] },
  { c: 'TV', p: 'O Velho Guerreiro era o apelido de…', alts: ['Chacrinha', 'Silvio Santos', 'Jô Soares', 'Dercy Gonçalves'] },
  { c: 'TV', p: 'Que seriado tinha o robô dizendo "Perigo, Will Robinson!"?', alts: ['Perdidos no Espaço', 'Jornada nas Estrelas', 'Túnel do Tempo', 'Terra de Gigantes'] },
  { c: 'TV', p: 'Os Trapalhões eram Didi, Dedé, Mussum e…', alts: ['Zacarias', 'Zé Bonitinho', 'Golias', 'Trindade'] },
  { c: 'TV', p: 'Qual programa infantil tinha a nave da Fada Bela e o Fofão?', alts: ['Balão Mágico', 'TV Colosso', 'Cavalo Amarelo', 'Rá-Tim-Bum'] },
  { c: 'Cinema', p: 'Quem dirigiu "Tubarão" (1975)?', alts: ['Steven Spielberg', 'George Lucas', 'Francis Ford Coppola', 'Martin Scorsese'] },
  { c: 'Cinema', p: 'Em "De Volta para o Futuro", qual carro vira máquina do tempo?', alts: ['DeLorean', 'Mustang', 'Fusca', 'Camaro'] },
  { c: 'Cinema', p: 'Qual boneco assassino aterrorizou os cinemas em 1988?', alts: ['Chucky', 'Annabelle', 'Pinóquio', 'Billy'] },
  { c: 'Cinema', p: '"E.T." queria, acima de tudo…', alts: ['Telefonar para casa', 'Comer chocolate', 'Andar de bicicleta', 'Ver televisão'] },
  { c: 'Cinema', p: 'Quem era o par romântico de Kate Winslet em "Titanic"?', alts: ['Leonardo DiCaprio', 'Brad Pitt', 'Tom Cruise', 'Johnny Depp'] },
  { c: 'Anos Dourados', p: 'Qual era a moeda do Brasil antes do Real?', alts: ['Cruzeiro Real', 'Cruzado Novo', 'Mil-réis', 'Peso'] },
  { c: 'Anos Dourados', p: 'O fusca era carro da qual montadora?', alts: ['Volkswagen', 'Ford', 'Chevrolet', 'Fiat'] },
  { c: 'Anos Dourados', p: 'Que eletrodoméstico "revolucionou" as cozinhas dos anos 50?', alts: ['A geladeira', 'O micro-ondas', 'A airfryer', 'A lava-louças'] },
  { c: 'Anos Dourados', p: 'Em que década o Brasil ganhou sua primeira Copa do Mundo?', alts: ['1950 (em 1958)', '1970', '1940', '1930'] },
  { c: 'Anos Dourados', p: 'Qual cidade foi capital do Brasil antes de Brasília?', alts: ['Rio de Janeiro', 'São Paulo', 'Salvador', 'Ouro Preto'] },
  { c: 'Anos Dourados', p: 'O "orelhão" era o nome popular do…', alts: ['Telefone público', 'Rádio de pilha', 'Toca-discos', 'Televisor'] },
  { c: 'Anos Dourados', p: 'Que aparelho tocava as fitas K7?', alts: ['O toca-fitas', 'A vitrola', 'O videocassete', 'O gramofone'] },
  { c: 'Anos Dourados', p: 'Pelé marcou seu milésimo gol em 1969 em qual estádio?', alts: ['Maracanã', 'Pacaembu', 'Vila Belmiro', 'Mineirão'] },
  { c: 'Brincadeiras', p: 'Qual brinquedo girava preso ao dedo por um barbante?', alts: ['Ioiô', 'Pião', 'Bilboquê', 'Peteca'] },
  { c: 'Brincadeiras', p: 'No jogo de bolinha de gude, a bolinha grande e valiosa era a…', alts: ['Bolão', 'Cebolão', 'Berlinde', 'Peteca'] },
  { c: 'Brincadeiras', p: '"Salada, saladinha, bem temperadinha…" é cantiga de qual brincadeira?', alts: ['Pular corda', 'Amarelinha', 'Ciranda', 'Passa-anel'] },
  { c: 'Brincadeiras', p: 'Qual videogame trouxe o Mario para as casas nos anos 80?', alts: ['Nintendinho (NES)', 'Atari 2600', 'Mega Drive', 'Odyssey'] },
  { c: 'Brincadeiras', p: 'A amarelinha termina no…', alts: ['Céu', 'Inferno', 'Mar', 'Sol'] },
  { c: 'Brincadeiras', p: 'Que figurinha "premiada" batia todas no bafo?', alts: ['A brilhosa', 'A repetida', 'A rasgada', 'A dobrada'] },
]
